name: release

on:
  push:
    tags:
      - '*'

jobs:
  release-go-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Unshallow repo
        run: git fetch --prune --unshallow
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm # 或 pnpm / yarn
      - name: Install dependencies
        run: pnpm i
      - name: Build webapp
        run: |
          pnpm run build
          cp -r dist server/ui
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x
      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          args: release --clean
          workdir: ./server/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
